/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-secondary": "var(--color-on-secondary)",
        "outline-variant": "var(--color-outline-variant)",
        "error-container": "var(--color-error-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-background": "var(--color-on-background)",
        "primary-container": "var(--color-primary-container)",
        "secondary": "var(--color-secondary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        background: "var(--color-background)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-variant": "var(--color-surface-variant)",
        tertiary: "var(--color-tertiary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "inverse-surface": "var(--color-inverse-surface)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        primary: "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-active": "var(--color-primary-active)",
        "primary-light": "var(--color-primary-light)",
        "primary-border": "var(--color-primary-border)",
        success: "var(--color-success)",
        "on-success": "var(--color-on-success)",
        "success-container": "var(--color-success-container)",
        "on-success-container": "var(--color-on-success-container)",
        outline: "var(--color-outline)",
        error: "var(--color-error)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-error-container": "var(--color-on-error-container)",
        
        // Aliases for compatibility with legacy components during transition
        sidebar: "var(--color-surface-container-low)",
        card: "var(--color-surface-container-low)",
        border: "var(--color-outline-variant)",
        danger: "var(--color-error)",
        text: "var(--color-on-surface)",
        muted: "var(--color-on-surface-variant)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px"
      },
      spacing: {
        "container-padding": "24px",
        "density-compact": "8px",
        "density-comfortable": "16px",
        unit: "4px",
        gutter: "24px", // Updated from 16px to 24px per DESIGN.md
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
