"""Add hardware inventory table

Revision ID: 152747f4f71b
Revises: b1ae2e96b716
Create Date: 2026-07-30 00:22:05.406250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "152747f4f71b"
down_revision: Union[str, Sequence[str], None] = "b1ae2e96b716"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hardware_inventory",
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("manufacturer", sa.String(length=255), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("serial_number", sa.String(length=255), nullable=False),
        sa.Column("bios_version", sa.String(length=255), nullable=False),
        sa.Column("bios_manufacturer", sa.String(length=255), nullable=False),
        sa.Column("bios_release_date", sa.String(length=255), nullable=False),
        sa.Column("motherboard", sa.String(length=255), nullable=False),
        sa.Column("cpu_name", sa.String(length=255), nullable=False),
        sa.Column("cpu_architecture", sa.String(length=100), nullable=False),
        sa.Column("cpu_cores", sa.Integer(), nullable=False),
        sa.Column("cpu_logical_processors", sa.Integer(), nullable=False),
        sa.Column("installed_ram_bytes", sa.BigInteger(), nullable=False),
        sa.Column("tpm_version", sa.String(length=50), nullable=True),
        sa.Column("secure_boot_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_virtual", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hardware_inventory_endpoint_id"),
        "hardware_inventory",
        ["endpoint_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_hardware_inventory_id"), "hardware_inventory", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hardware_inventory_id"), table_name="hardware_inventory")
    op.drop_index(
        op.f("ix_hardware_inventory_endpoint_id"), table_name="hardware_inventory"
    )
    op.drop_table("hardware_inventory")
    # ### end Alembic commands ###
