"""canonical_identity

Revision ID: 47132bd48eb0
Revises: 4bb61beca310
Create Date: 2026-08-06 16:35:06.498328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "47132bd48eb0"
down_revision: Union[str, Sequence[str], None] = "4bb61beca310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column(
        "endpoints", sa.Column("agent_id", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "endpoints", sa.Column("identity_version", sa.Integer(), nullable=True)
    )
    op.add_column(
        "endpoints", sa.Column("identity_anomaly", sa.Boolean(), nullable=True)
    )

    # Populate existing rows
    import uuid
    from sqlalchemy.sql import text

    conn = op.get_bind()
    res = conn.execute(text("SELECT id FROM endpoints"))
    for row in res:
        conn.execute(
            text(
                "UPDATE endpoints SET agent_id = :agent_id, identity_version = 1, identity_anomaly = false WHERE id = :id"
            ),
            {"agent_id": str(uuid.uuid4()), "id": row[0]},
        )

    # Alter columns to be not nullable
    op.alter_column("endpoints", "agent_id", nullable=False)
    op.alter_column("endpoints", "identity_version", nullable=False)
    op.alter_column("endpoints", "identity_anomaly", nullable=False)

    op.create_index(
        op.f("ix_endpoints_agent_id"), "endpoints", ["agent_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_endpoints_agent_id"), table_name="endpoints")
    op.drop_column("endpoints", "identity_anomaly")
    op.drop_column("endpoints", "identity_version")
    op.drop_column("endpoints", "agent_id")
    # ### end Alembic commands ###
