"""Add endpoints table

Revision ID: b1ae2e96b716
Revises: 99fe757562ae
Create Date: 2026-07-29 23:57:47.099869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b1ae2e96b716"
down_revision: Union[str, Sequence[str], None] = "99fe757562ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoints",
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("os_version", sa.String(length=255), nullable=False),
        sa.Column("hardware_hash", sa.String(length=64), nullable=False),
        sa.Column("mac_addresses", sa.JSON(), nullable=True),
        sa.Column("ip_addresses", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("config_version", sa.String(length=50), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_endpoints_hardware_hash"), "endpoints", ["hardware_hash"], unique=True
    )
    op.create_index(op.f("ix_endpoints_id"), "endpoints", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_endpoints_id"), table_name="endpoints")
    op.drop_index(op.f("ix_endpoints_hardware_hash"), table_name="endpoints")
    op.drop_table("endpoints")
    # ### end Alembic commands ###
