from enum import Enum


class CommandStatus(str, Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class CommandType(str, Enum):
    PING = "PING"
    RUN_INVENTORY = "RUN_INVENTORY"
    REFRESH_POLICY = "REFRESH_POLICY"
    RESTART_SERVICE = "RESTART_SERVICE"
    RESTART_AGENT = "RESTART_AGENT"
    SYNC_NOW = "SYNC_NOW"
    SYSTEM_SCAN = "SYSTEM_SCAN"
    AGENT_UPDATE = "AGENT_UPDATE"
    PATCH_INSTALL = "PATCH_INSTALL"
    PROCESS_KILL = "PROCESS_KILL"
    GET_PROCESS_LIST = "GET_PROCESS_LIST"
    GET_SERVICE_LIST = "GET_SERVICE_LIST"
    CUSTOM_SCRIPT = "CUSTOM_SCRIPT"
